# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: backupdrbackupplanassociation-dep
spec:
  machineType: n1-standard-1
  zone: us-central1-a
  bootDisk:
    initializeParams:
      sourceImageRef:
        external: debian-cloud/debian-11
---
apiVersion: backupdr.cnrm.cloud.google.com/v1alpha1
kind: BackupDRBackupVault
metadata:
  name: backupdrbackupplanassociation-dep
spec:
  location: us-central1
  backupMinimumEnforcedRetentionDuration: "86400s"
---
apiVersion: backupdr.cnrm.cloud.google.com/v1alpha1
kind: BackupDRBackupPlan
metadata:
  name: backupdrbackupplanassociation-dep
spec:
  location: us-central1
  resourceType: "compute.googleapis.com/Instance"
  backupVaultRef:
    name: "backupdrbackupplanassociation-dep"
  backupRules:
    - ruleID: "daily-backups"
      backupRetentionDays: 30
      standardSchedule:
        recurrenceType: "DAILY"
        backupWindow:
          startHourOfDay: 6
          endHourOfDay: 10
        timeZone: "America/New_York"
