# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: core.cnrm.cloud.google.com/v1alpha1
kind: ServiceMapping
metadata:
  name: serviceusage.cnrm.cloud.google.com
  namespace: cnrm-system
spec:
  name: ServiceUsage
  version: v1beta1
  serviceHostName: "serviceusage.googleapis.com"
  resources:
    - name: google_project_service
      kind: Service
      idTemplate: "{{project}}/{{service}}"
      idTemplateCanBeUsedToMatchResourceName: true
      resourceAvailableInAssetInventory: true
      metadataMapping:
        name: service
      resourceID:
        targetField: service
      containers:
        - type: project
          tfField: project
      ignoredFields:
        - disable_on_destroy
      directives:
        - disable_on_destroy
        - disable_dependent_services
      resourceReferences:
        - tfField: project
          key: projectRef
          description: |-
            The project that this resource belongs to.
          gvk:
            kind: Project
            version: v1beta1
            group: resourcemanager.cnrm.cloud.google.com
      hierarchicalReferences:
      - type: project
        key: projectRef
    - name: google_project_service_identity
      kind: ServiceIdentity
      idTemplate: "projects/{{project}}/services/{{service}}"
      # doesn't have a url to fetch this resource
      idTemplateCanBeUsedToMatchResourceName: false
      skipImport: true
      unreadable: true
      reconciliationIntervalInSeconds: 0
      metadataMapping:
        name: service
      resourceID:
        targetField: service
      iamMemberReferenceConfig:
        targetField: email
        valueTemplate: "serviceAccount:{{value}}"
      resourceReferences:
        - tfField: project
          key: projectRef
          description: |-
            The project that this resource belongs to.
          gvk:
            kind: Project
            version: v1beta1
            group: resourcemanager.cnrm.cloud.google.com
      hierarchicalReferences:
        - type: project
          key: projectRef
