apiVersion: v1
data:
  cnrm.controller: gcr.io/maqiuyu-kcc-test-2/cnrm/controller:b76c630
  cnrm.deletiondefender: gcr.io/maqiuyu-kcc-test-2/cnrm/deletiondefender:b76c630
  cnrm.recorder: gcr.io/maqiuyu-kcc-test-2/cnrm/recorder:b76c630
  cnrm.unmanageddetector: gcr.io/maqiuyu-kcc-test-2/cnrm/unmanageddetector:b76c630
  cnrm.webhook: gcr.io/maqiuyu-kcc-test-2/cnrm/webhook:b76c630
  prom-to-sd: gcr.io/gke-release/prometheus-to-sd:v0.11.12-gke.11
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/image-map: Images deployed by operator
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cnrm.cloud.google.com/operator-system: "true"
  name: config-images
  namespace: configconnector-operator-system
