apiVersion: v1
data:
  cnrm.controller: gcr.io/gke-release/cnrm/controller:1.134.0
  cnrm.deletiondefender: gcr.io/gke-release/cnrm/deletiondefender:1.134.0
  cnrm.recorder: gcr.io/gke-release/cnrm/recorder:1.134.0
  cnrm.unmanageddetector: gcr.io/gke-release/cnrm/unmanageddetector:1.134.0
  cnrm.webhook: gcr.io/gke-release/cnrm/webhook:1.134.0
  prom-to-sd: gcr.io/gke-release/prometheus-to-sd:v0.12.1-gke.17
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/image-map: Images deployed by operator
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cnrm.cloud.google.com/operator-system: "true"
  name: config-images
  namespace: configconnector-operator-system
