apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: spannerbackupschedules.spanner.cnrm.cloud.google.com
spec:
  group: spanner.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: SpannerBackupSchedule
    listKind: SpannerBackupScheduleList
    plural: spannerbackupschedules
    shortNames:
    - gcpspannerbackupschedule
    - gcpspannerbackupschedules
    singular: spannerbackupschedule
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SpannerBackupSchedule is the Schema for the SpannerBackupSchedule
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SpannerBackupScheduleSpec defines the desired state of SpannerBackupSchedule
            properties:
              databaseRef:
                description: The reference to the parent database
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed SpannerDatabase
                      resource. Should be in the format "projects/{{projectID}}/locations/{{location}}/databases/{{databaseID}}".
                    type: string
                  name:
                    description: The name of a SpannerDatabase resource.
                    type: string
                  namespace:
                    description: The namespace of a SpannerDatabase resource.
                    type: string
                type: object
              encryptionConfig:
                description: Optional. The encryption configuration that will be used
                  to encrypt the backup. If this field is not specified, the backup
                  will use the same encryption configuration as the database.
                properties:
                  encryptionType:
                    description: Required. The encryption type of the backup.
                    type: string
                  kmsKeyName:
                    description: Optional. The Cloud KMS key that will be used to
                      protect the backup. This field should be set only when [encryption_type][google.spanner.admin.database.v1.CreateBackupEncryptionConfig.encryption_type]
                      is `CUSTOMER_MANAGED_ENCRYPTION`. Values are of the form `projects/<project>/locations/<location>/keyRings/<key_ring>/cryptoKeys/<kms_key_name>`.
                    type: string
                  kmsKeyNames:
                    description: |-
                      Optional. Specifies the KMS configuration for the one or more keys used to
                       protect the backup. Values are of the form
                       `projects/<project>/locations/<location>/keyRings/<key_ring>/cryptoKeys/<kms_key_name>`.

                       The keys referenced by kms_key_names must fully cover all
                       regions of the backup's instance configuration. Some examples:
                       * For single region instance configs, specify a single regional
                       location KMS key.
                       * For multi-regional instance configs of type GOOGLE_MANAGED,
                       either specify a multi-regional location KMS key or multiple regional
                       location KMS keys that cover all regions in the instance config.
                       * For an instance config of type USER_MANAGED, please specify only
                       regional location KMS keys to cover each region in the instance config.
                       Multi-regional location KMS keys are not supported for USER_MANAGED
                       instance configs.
                    items:
                      type: string
                    type: array
                type: object
              fullBackupSpec:
                description: The schedule creates only full backups.
                type: object
              incrementalBackupSpec:
                description: The schedule creates incremental backup chains.
                type: object
              instanceRef:
                description: The reference to the parent instance
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed SpannerInstance
                      resource. Should be in the format "projects/{{projectID}}/instances/{{instanceID}}".
                    type: string
                  name:
                    description: The name of a SpannerInstance resource.
                    type: string
                  namespace:
                    description: The namespace of a SpannerInstance resource.
                    type: string
                type: object
              projectRef:
                description: Immutable. The Project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed
                      by Config Connector.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must
                      be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
                x-kubernetes-validations:
                - message: ResourceID field is immutable
                  rule: self == oldSelf
              resourceID:
                description: The SpannerBackupSchedule name. If not given, the metadata.name
                  will be used.
                type: string
              retentionDuration:
                description: Optional. The retention duration of a backup that must
                  be at least 6 hours and at most 366 days. The backup is eligible
                  to be automatically deleted once the retention period has elapsed.
                type: string
              spec:
                description: Optional. The schedule specification based on which the
                  backup creations are triggered.
                properties:
                  cronSpec:
                    description: Cron style schedule specification.
                    properties:
                      text:
                        description: |-
                          Required. Textual representation of the crontab. User can customize the
                           backup frequency and the backup version time using the cron
                           expression. The version time must be in UTC timzeone.

                           The backup will contain an externally consistent copy of the
                           database at the version time. Allowed frequencies are 12 hour, 1 day,
                           1 week and 1 month. Examples of valid cron specifications:
                             * `0 2/12 * * * ` : every 12 hours at (2, 14) hours past midnight in UTC.
                             * `0 2,14 * * * ` : every 12 hours at (2,14) hours past midnight in UTC.
                             * `0 2 * * * `    : once a day at 2 past midnight in UTC.
                             * `0 2 * * 0 `    : once a week every Sunday at 2 past midnight in UTC.
                             * `0 2 8 * * `    : once a month on 8th day at 2 past midnight in UTC.
                        type: string
                    type: object
                type: object
            required:
            - projectRef
            type: object
          status:
            description: SpannerBackupScheduleStatus defines the config connector
              machine state of SpannerBackupSchedule
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the SpannerBackupSchedule resource
                  in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  updateTime:
                    description: Output only. The timestamp at which the backup schedule
                      was last updated
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
