apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/stability-level: alpha
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: appenginedomainmappings.appengine.cnrm.cloud.google.com
spec:
  group: appengine.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: AppEngineDomainMapping
    listKind: AppEngineDomainMappingList
    plural: appenginedomainmappings
    shortNames:
    - gcpappenginedomainmapping
    - gcpappenginedomainmappings
    singular: appenginedomainmapping
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AppEngineDomainMapping is the Schema for the AppEngineDomainMapping
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AppEngineDomainMappingSpec defines the desired state of AppEngineDomainMapping
            properties:
              overrideStrategy:
                description: 'Whether the domain creation should override any existing
                  mappings for this domain. By default, overrides are rejected. Default
                  value: "STRICT" Possible values: ["STRICT", "OVERRIDE"].'
                type: string
              project:
                description: The project that this resource belongs to.
                type: string
              resourceID:
                description: The AppEngineDomainMapping name. If not given, the metadata.name
                  will be used.
                type: string
              sslSettings:
                description: SSL configuration for this domain. If unconfigured, this
                  domain will not serve with SSL.
                properties:
                  certificateId:
                    description: |-
                      ID of the `AuthorizedCertificate` resource configuring SSL for the
                       application. Clearing this field will remove SSL support.

                       By default, a managed certificate is automatically created for every
                       domain mapping. To omit SSL support or to configure SSL manually, specify
                       `SslManagementType.MANUAL` on a `CREATE` or `UPDATE` request. You must
                       be authorized to administer the `AuthorizedCertificate` resource to
                       manually map it to a `DomainMapping` resource.
                       Example: `12345`.
                    type: string
                  pendingManagedCertificateId:
                    description: |-
                      ID of the managed `AuthorizedCertificate` resource currently being
                       provisioned, if applicable. Until the new managed certificate has been
                       successfully provisioned, the previous SSL state will be preserved. Once
                       the provisioning process completes, the `certificate_id` field will reflect
                       the new managed certificate and this field will be left empty. To remove
                       SSL support while there is still a pending managed certificate, clear the
                       `certificate_id` field with an `UpdateDomainMappingRequest`.

                       @OutputOnly
                    type: string
                  sslManagementType:
                    description: SSL management type for this domain. If `AUTOMATIC`,
                      a managed certificate is automatically provisioned. If `MANUAL`,
                      `certificate_id` must be manually specified in order to configure
                      SSL for this domain.
                    type: string
                required:
                - sslManagementType
                type: object
            type: object
          status:
            description: AppEngineDomainMappingStatus defines the config connector
              machine state of AppEngineDomainMapping
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the AppEngineDomainMapping resource
                  in GCP.
                type: string
              name:
                description: 'Full path to the `DomainMapping` resource in the API.
                  Example: `apps/myapp/domainMapping/example.com`.'
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              resourceRecords:
                description: The resource records required to configure this domain
                  mapping. These records must be added to the domain's DNS configuration
                  in order to serve the application via this domain mapping.
                items:
                  properties:
                    name:
                      description: 'Relative name of the object affected by this record.
                        Only applicable for CNAME records. Example: ''www''.'
                      type: string
                    rrdata:
                      description: Data for this record. Values vary by record type,
                        as defined in RFC 1035 (section 5) and RFC 1034 (section 3.6.1).
                      type: string
                    type:
                      description: 'Resource record type. Example: ''AAAA''. Possible
                        values: ["A", "AAAA", "CNAME"]'
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
