apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/stability-level: stable
    cnrm.cloud.google.com/system: "true"
  name: computefirewallpolicyrules.compute.cnrm.cloud.google.com
spec:
  group: compute.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: ComputeFirewallPolicyRule
    listKind: ComputeFirewallPolicyRuleList
    plural: computefirewallpolicyrules
    shortNames:
    - gcpcomputefirewallpolicyrule
    - gcpcomputefirewallpolicyrules
    singular: computefirewallpolicyrule
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: ComputeFirewallPolicyRule is the Schema for the compute API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              action:
                description: 'The Action to perform when the client connection triggers
                  the rule. Valid actions for firewall rules are: "allow", "deny",
                  "apply_security_profile_group" and "goto_next". Valid actions for
                  packet mirroring rules are: "mirror", "do_not_mirror" and "goto_next".'
                type: string
              description:
                description: An optional description for this resource.
                type: string
              direction:
                description: The direction in which this rule applies. Check the Direction
                  enum for the list of possible values.
                type: string
              disabled:
                description: Denotes whether the firewall policy rule is disabled.
                  When set to true, the firewall policy rule is not enforced and traffic
                  behaves as if it did not exist. If this is unspecified, the firewall
                  policy rule will be enabled.
                type: boolean
              enableLogging:
                description: 'Denotes whether to enable logging for a particular rule.
                  If logging is enabled, logs will be exported to the configured export
                  destination in Stackdriver. Logs may be exported to BigQuery or
                  Pub/Sub. Note: you cannot enable logging on "goto_next" rules.'
                type: boolean
              firewallPolicyRef:
                description: Immutable.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed ComputeFirewallPolicy
                      resource. Should be in the format `locations/global/firewallPolicies/{{firewallPolicyID}}`.
                    type: string
                  name:
                    description: The `name` field of a `ComputeFirewallPolicy` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `ComputeFirewallPolicy`
                      resource.
                    type: string
                type: object
              match:
                description: A match condition that incoming traffic is evaluated
                  against. If it evaluates to true, the corresponding 'action' is
                  enforced.
                properties:
                  destAddressGroups:
                    description: Address groups which should be matched against the
                      traffic destination. Maximum number of destination address groups
                      is 10.
                    items:
                      type: string
                    type: array
                  destFqdns:
                    description: Fully Qualified Domain Name (FQDN) which should be
                      matched against traffic destination. Maximum number of destination
                      fqdn allowed is 100.
                    items:
                      type: string
                    type: array
                  destIPRanges:
                    description: CIDR IP address range. Maximum number of destination
                      CIDR IP ranges allowed is 5000.
                    items:
                      type: string
                    type: array
                  destRegionCodes:
                    description: Region codes whose IP addresses will be used to match
                      for destination of traffic. Should be specified as 2 letter
                      country code defined as per ISO 3166 alpha-2 country codes.
                      ex."US" Maximum number of dest region codes allowed is 5000.
                    items:
                      type: string
                    type: array
                  destThreatIntelligences:
                    description: Names of Network Threat Intelligence lists. The IPs
                      in these lists will be matched against traffic destination.
                    items:
                      type: string
                    type: array
                  layer4Configs:
                    description: Pairs of IP protocols and ports that the rule should
                      match.
                    items:
                      properties:
                        ipProtocol:
                          description: The IP protocol to which this rule applies.
                            The protocol type is required when creating a firewall
                            rule. This value can either be one of the following well
                            known protocol strings (tcp, udp, icmp, esp, ah, ipip,
                            sctp), or the IP protocol number.
                          type: string
                        ports:
                          description: 'An optional list of ports to which this rule
                            applies. This field is only applicable for UDP or TCP
                            protocol. Each entry must be either an integer or a range.
                            If not specified, this rule applies to connections through
                            any port. Example inputs include: ["22"], ["80","443"],
                            and ["12345-12349"].'
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  srcAddressGroups:
                    description: Address groups which should be matched against the
                      traffic source. Maximum number of source address groups is 10.
                    items:
                      type: string
                    type: array
                  srcFqdns:
                    description: Fully Qualified Domain Name (FQDN) which should be
                      matched against traffic source. Maximum number of source fqdn
                      allowed is 100.
                    items:
                      type: string
                    type: array
                  srcIPRanges:
                    description: CIDR IP address range. Maximum number of source CIDR
                      IP ranges allowed is 5000.
                    items:
                      type: string
                    type: array
                  srcRegionCodes:
                    description: Region codes whose IP addresses will be used to match
                      for source of traffic. Should be specified as 2 letter country
                      code defined as per ISO 3166 alpha-2 country codes. ex."US"
                      Maximum number of source region codes allowed is 5000.
                    items:
                      type: string
                    type: array
                  srcThreatIntelligences:
                    description: Names of Network Threat Intelligence lists. The IPs
                      in these lists will be matched against traffic source.
                    items:
                      type: string
                    type: array
                type: object
              priority:
                description: An integer indicating the priority of a rule in the list.
                  The priority must be a positive value between 0 and 2147483647.
                  Rules are evaluated from highest to lowest priority where 0 is the
                  highest priority and 2147483647 is the lowest priority.
                format: int32
                type: integer
              targetResources:
                description: A list of network resource URLs to which this rule applies.
                  This field allows you to control which network's VMs get this rule.
                  If this field is left blank, all VMs within the organization will
                  receive the rule.
                items:
                  oneOf:
                  - not:
                      required:
                      - external
                    required:
                    - name
                  - not:
                      anyOf:
                      - required:
                        - name
                      - required:
                        - namespace
                    required:
                    - external
                  properties:
                    external:
                      description: A reference to an externally-managed Compute Network
                        resource. Should be in the format `projects/{{projectID}}/global/networks/{{network}}`.
                      type: string
                    name:
                      description: The `name` field of a `ComputeNetwork` resource.
                      type: string
                    namespace:
                      description: The `namespace` field of a `ComputeNetwork` resource.
                      type: string
                  type: object
                type: array
              targetServiceAccounts:
                description: A list of service accounts indicating the sets of instances
                  that are applied with this rule.
                items:
                  oneOf:
                  - not:
                      required:
                      - external
                    required:
                    - name
                  - not:
                      anyOf:
                      - required:
                        - name
                      - required:
                        - namespace
                    required:
                    - external
                  properties:
                    external:
                      description: The `email` field of an `IAMServiceAccount` resource.
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                    namespace:
                      description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                      type: string
                  type: object
                type: array
            required:
            - firewallPolicyRef
            type: object
          status:
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique Config Connector specifier for the resource
                  in GCP.
                type: string
              kind:
                description: '[Output only] Type of the resource. Returns compute#firewallPolicyRule
                  for firewall rules and compute#packetMirroringRule for packet mirroring
                  rules.'
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              ruleTupleCount:
                description: '[Output Only] Calculation of the complexity of a single
                  firewall policy rule.'
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
