apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: filestoreinstances.filestore.cnrm.cloud.google.com
spec:
  group: filestore.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: FilestoreInstance
    listKind: FilestoreInstanceList
    plural: filestoreinstances
    shortNames:
    - gcpfilestoreinstance
    - gcpfilestoreinstances
    singular: filestoreinstance
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FilestoreInstance is the Schema for the FilestoreInstance API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FilestoreInstanceSpec defines the desired state of FilestoreInstance
            properties:
              description:
                description: The description of the instance (2048 characters or less).
                type: string
              fileShares:
                description: File system shares on the instance. For this version,
                  only a single file share is supported.
                items:
                  properties:
                    capacityGB:
                      description: File share capacity in gigabytes (GB). Filestore
                        defines 1 GB as 1024^3 bytes.
                      format: int64
                      type: integer
                    name:
                      description: Required. The name of the file share. Must use
                        1-16 characters for the basic service tier and 1-63 characters
                        for all other service tiers. Must use lowercase letters, numbers,
                        or underscores `[a-z0-9_]`. Must start with a letter. Immutable.
                      type: string
                    nfsExportOptions:
                      description: Nfs Export Options. There is a limit of 10 export
                        options per file share.
                      items:
                        properties:
                          accessMode:
                            description: Either READ_ONLY, for allowing only read
                              requests on the exported directory, or READ_WRITE, for
                              allowing both read and write requests. The default is
                              READ_WRITE.
                            type: string
                          anonGid:
                            description: An integer representing the anonymous group
                              id with a default value of 65534. Anon_gid may only
                              be set with squash_mode of ROOT_SQUASH.  An error will
                              be returned if this field is specified for other squash_mode
                              settings.
                            format: int64
                            type: integer
                          anonUid:
                            description: An integer representing the anonymous user
                              id with a default value of 65534. Anon_uid may only
                              be set with squash_mode of ROOT_SQUASH.  An error will
                              be returned if this field is specified for other squash_mode
                              settings.
                            format: int64
                            type: integer
                          ipRanges:
                            description: List of either an IPv4 addresses in the format
                              `{octet1}.{octet2}.{octet3}.{octet4}` or CIDR ranges
                              in the format `{octet1}.{octet2}.{octet3}.{octet4}/{mask
                              size}` which may mount the file share. Overlapping IP
                              ranges are not allowed, both within and across NfsExportOptions.
                              An error will be returned. The limit is 64 IP ranges/addresses
                              for each FileShareConfig among all NfsExportOptions.
                            items:
                              type: string
                            type: array
                          squashMode:
                            description: Either NO_ROOT_SQUASH, for allowing root
                              access on the exported directory, or ROOT_SQUASH, for
                              not allowing root access. The default is NO_ROOT_SQUASH.
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
              kmsKeyName:
                description: The KMS key name used for data encryption.
                type: string
              location:
                description: Immutable. The zone for this filestore instance.
                type: string
              networks:
                description: VPC networks to which the instance is connected. For
                  this version, only a single network is supported.
                items:
                  properties:
                    connectMode:
                      description: The network connect mode of the Filestore instance.
                        If not provided, the connect mode defaults to DIRECT_PEERING.
                      type: string
                    modes:
                      description: Internet protocol versions for which the instance
                        has IP addresses assigned. For this version, only MODE_IPV4
                        is supported.
                      items:
                        type: string
                      type: array
                    network:
                      description: The name of the Google Compute Engine [VPC network](https://cloud.google.com/vpc/docs/vpc)
                        to which the instance is connected.
                      type: string
                    reservedIPRange:
                      description: |-
                        Optional, reserved_ip_range can have one of the following two types of
                         values.

                         * CIDR range value when using DIRECT_PEERING connect mode.
                         * [Allocated IP address
                         range](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address)
                         when using PRIVATE_SERVICE_ACCESS connect mode.

                         When the name of an allocated IP address range is specified, it must be one
                         of the ranges associated with the private service access connection.
                         When specified as a direct CIDR value, it must be a /29 CIDR block for
                         Basic tier, a /24 CIDR block for High Scale tier, or a /26 CIDR block for
                         Enterprise tier in one of the [internal IP address
                         ranges](https://www.arin.net/reference/research/statistics/address_filters/)
                         that identifies the range of IP addresses reserved for this instance. For
                         example, 10.0.0.0/29, 192.168.0.0/24 or 192.168.0.0/26, respectively. The
                         range you specify can't overlap with either existing subnets or assigned IP
                         address ranges for other Filestore instances in the selected VPC
                         network.
                      type: string
                  type: object
                type: array
              projectRef:
                description: The project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed
                      by Config Connector.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must
                      be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
              resourceID:
                description: The FilestoreInstance name. If not given, the metadata.name
                  will be used.
                type: string
              tier:
                description: The service tier of the instance.
                type: string
            required:
            - location
            - projectRef
            type: object
          status:
            description: FilestoreInstanceStatus defines the config connector machine
              state of FilestoreInstance
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the FilestoreInstance resource
                  in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  createTime:
                    description: Output only. The time when the instance was created.
                    type: string
                  name:
                    description: Output only. The resource name of the instance, in
                      the format `projects/{project}/locations/{location}/instances/{instance}`.
                    type: string
                  networks:
                    description: VPC networks to which the instance is connected.
                      For this version, only a single network is supported.
                    items:
                      properties:
                        ipAddresses:
                          description: Output only. IPv4 addresses in the format `{octet1}.{octet2}.{octet3}.{octet4}`
                            or IPv6 addresses in the format `{block1}:{block2}:{block3}:{block4}:{block5}:{block6}:{block7}:{block8}`.
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  satisfiesPzi:
                    description: Output only. Reserved for future use.
                    type: boolean
                  satisfiesPzs:
                    description: Output only. Reserved for future use.
                    type: boolean
                  state:
                    description: Output only. The instance state.
                    type: string
                  statusMessage:
                    description: Output only. Additional information about the instance
                      state, if available.
                    type: string
                  suspensionReasons:
                    description: Output only. Field indicates all the reasons the
                      instance is in "SUSPENDED" state.
                    items:
                      type: string
                    type: array
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
