apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: workflowsexecutions.workflows.cnrm.cloud.google.com
spec:
  group: workflows.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: WorkflowsExecution
    listKind: WorkflowsExecutionList
    plural: workflowsexecutions
    shortNames:
    - gcpworkflowsexecution
    - gcpworkflowsexecutions
    singular: workflowsexecution
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: WorkflowsExecution is the Schema for the WorkflowsExecution API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WorkflowsExecutionSpec defines the desired state of WorkflowsExecution
            properties:
              argument:
                description: |-
                  Input parameters of the execution represented as a JSON string.
                   The size limit is 32KB.

                   *Note*: If you are using the REST API directly to run your workflow, you
                   must escape any JSON string value of `argument`. Example:
                   `'{"argument":"{\"firstName\":\"FIRST\",\"lastName\":\"LAST\"}"}'`
                type: string
              callLogLevel:
                description: The call logging level associated to this execution.
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Labels associated with this execution. Labels can contain
                  at most 64 entries. Keys and values can be no longer than 63 characters
                  and can only contain lowercase letters, numeric characters, underscores,
                  and dashes. Label keys must start with a letter. International characters
                  are allowed. By default, labels are inherited from the workflow
                  but are overridden by any labels associated with the execution.
                type: object
              parent:
                description: 'Required. Name of the workflow for which an execution
                  should be created. Format: projects/{project}/locations/{location}/workflows/{workflow}.
                  The latest revision of the workflow will be used.'
                properties:
                  location:
                    description: Required. The location of the application.
                    type: string
                  projectRef:
                    description: Required. The host project of the application.
                    oneOf:
                    - not:
                        required:
                        - external
                      required:
                      - name
                      - kind
                    - not:
                        anyOf:
                        - required:
                          - name
                        - required:
                          - namespace
                        - required:
                          - kind
                      required:
                      - external
                    properties:
                      external:
                        description: The `projectID` field of a project, when not
                          managed by Config Connector.
                        type: string
                      kind:
                        description: The kind of the Project resource; optional but
                          must be `Project` if provided.
                        type: string
                      name:
                        description: The `name` field of a `Project` resource.
                        type: string
                      namespace:
                        description: The `namespace` field of a `Project` resource.
                        type: string
                    type: object
                  workflowRef:
                    description: Required.
                    oneOf:
                    - not:
                        required:
                        - external
                      required:
                      - name
                    - not:
                        anyOf:
                        - required:
                          - name
                        - required:
                          - namespace
                      required:
                      - external
                    properties:
                      external:
                        description: The StorageBucket selfLink, when not managed
                          by Config Connector.
                        type: string
                      name:
                        description: The `name` field of a `StorageBucket` resource.
                        type: string
                      namespace:
                        description: The `namespace` field of a `StorageBucket` resource.
                        type: string
                    type: object
                type: object
              resourceID:
                description: The WorkflowsExecution name. If not given, the metadata.name
                  will be used.
                type: string
            type: object
          status:
            description: WorkflowsExecutionStatus defines the config connector machine
              state of WorkflowsExecution
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the WorkflowsExecution resource
                  in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  duration:
                    description: Output only. Measures the duration of the execution.
                    type: string
                  endTime:
                    description: Output only. Marks the end of execution, successful
                      or not.
                    type: string
                  error:
                    description: Output only. The error which caused the execution
                      to finish prematurely. The value is only present if the execution's
                      state is `FAILED` or `CANCELLED`.
                    properties:
                      context:
                        description: Human-readable stack trace string.
                        type: string
                      payload:
                        description: Error message and data returned represented as
                          a JSON string.
                        type: string
                      stackTrace:
                        description: Stack trace with detailed information of where
                          error was generated.
                        properties:
                          elements:
                            description: An array of stack elements.
                            items:
                              properties:
                                position:
                                  description: The source position information of
                                    the stack trace element.
                                  properties:
                                    column:
                                      description: The source code column position
                                        (of the line) the current instruction was
                                        generated from.
                                      format: int64
                                      type: integer
                                    length:
                                      description: The number of bytes of source code
                                        making up this stack trace element.
                                      format: int64
                                      type: integer
                                    line:
                                      description: The source code line number the
                                        current instruction was generated from.
                                      format: int64
                                      type: integer
                                  type: object
                                routine:
                                  description: The routine where the error occurred.
                                  type: string
                                step:
                                  description: The step the error occurred at.
                                  type: string
                              type: object
                            type: array
                        type: object
                    type: object
                  result:
                    description: Output only. Output of the execution represented
                      as a JSON string. The value can only be present if the execution's
                      state is `SUCCEEDED`.
                    type: string
                  startTime:
                    description: Output only. Marks the beginning of execution.
                    type: string
                  state:
                    description: Output only. Current state of the execution.
                    type: string
                  stateError:
                    description: Output only. Error regarding the state of the Execution
                      resource. For example, this field will have error details if
                      the execution data is unavailable due to revoked KMS key permissions.
                    properties:
                      details:
                        description: Provides specifics about the error.
                        type: string
                      type:
                        description: The type of this state error.
                        type: string
                    type: object
                  status:
                    description: Output only. Status tracks the current steps and
                      progress data of this execution.
                    properties:
                      currentSteps:
                        description: A list of currently executing or last executed
                          step names for the workflow execution currently running.
                          If the workflow has succeeded or failed, this is the last
                          attempted or executed step. Presently, if the current step
                          is inside a subworkflow, the list only includes that step.
                          In the future, the list will contain items for each step
                          in the call stack, starting with the outermost step in the
                          `main` subworkflow, and ending with the most deeply nested
                          step.
                        items:
                          properties:
                            routine:
                              description: Name of a routine within the workflow.
                              type: string
                            step:
                              description: Name of a step within the routine.
                              type: string
                          type: object
                        type: array
                    type: object
                  workflowRevisionID:
                    description: Output only. Revision of the workflow this execution
                      is using.
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
