apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: accesscontextmanageraccesslevels.accesscontextmanager.cnrm.cloud.google.com
spec:
  group: accesscontextmanager.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: AccessContextManagerAccessLevel
    listKind: AccessContextManagerAccessLevelList
    plural: accesscontextmanageraccesslevels
    shortNames:
    - gcpaccesscontextmanageraccesslevel
    - gcpaccesscontextmanageraccesslevels
    singular: accesscontextmanageraccesslevel
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: AccessContextManagerAccessLevel is the Schema for the AccessContextManagerAccessLevel
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AccessContextManagerAccessLevelSpec defines the desired state
              of AccessContextManagerAccessLevel
            properties:
              accessPolicyRef:
                description: The AccessPolicy that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: A reference to an externally managed AccessContextManagerAccessPolicy
                      resource. Should be in the format "projects/{{projectID}}/locations/{{location}}/accesspolicys/{{accesspolicyID}}".
                    type: string
                  name:
                    description: The name of a AccessContextManagerAccessPolicy resource.
                    type: string
                  namespace:
                    description: The namespace of a AccessContextManagerAccessPolicy
                      resource.
                    type: string
                type: object
              basic:
                description: A `BasicLevel` composed of `Conditions`.
                properties:
                  combiningFunction:
                    description: How the `conditions` list should be combined to determine
                      if a request is granted this `AccessLevel`. If AND is used,
                      each `Condition` in `conditions` must be satisfied for the `AccessLevel`
                      to be applied. If OR is used, at least one `Condition` in `conditions`
                      must be satisfied for the `AccessLevel` to be applied. Default
                      behavior is AND.
                    type: string
                  conditions:
                    description: Required. A list of requirements for the `AccessLevel`
                      to be granted.
                    items:
                      properties:
                        devicePolicy:
                          description: Device specific restrictions, all restrictions
                            must hold for the Condition to be true. If not specified,
                            all devices are allowed.
                          properties:
                            allowedDeviceManagementLevels:
                              description: Allowed device management levels, an empty
                                list allows all management levels.
                              items:
                                type: string
                              type: array
                            allowedEncryptionStatuses:
                              description: Allowed encryptions statuses, an empty
                                list allows all statuses.
                              items:
                                type: string
                              type: array
                            osConstraints:
                              description: Allowed OS versions, an empty list allows
                                all types and all versions.
                              items:
                                properties:
                                  minimumVersion:
                                    description: 'The minimum allowed OS version.
                                      If not set, any version of this OS satisfies
                                      the constraint. Format: `"major.minor.patch"`.
                                      Examples: `"10.5.301"`, `"9.2.1"`.'
                                    type: string
                                  osType:
                                    description: Required. The allowed OS type.
                                    type: string
                                  requireVerifiedChromeOS:
                                    description: Only allows requests from devices
                                      with a verified Chrome OS. Verifications includes
                                      requirements that the device is enterprise-managed,
                                      conformant to domain policies, and the caller
                                      has permission to call the API targeted by the
                                      request.
                                    type: boolean
                                type: object
                              type: array
                            requireAdminApproval:
                              description: Whether the device needs to be approved
                                by the customer admin.
                              type: boolean
                            requireCorpOwned:
                              description: Whether the device needs to be corp owned.
                              type: boolean
                            requireScreenlock:
                              description: Whether or not screenlock is required for
                                the DevicePolicy to be true. Defaults to `false`.
                              type: boolean
                          type: object
                        ipSubnetworks:
                          description: CIDR block IP subnetwork specification. May
                            be IPv4 or IPv6. Note that for a CIDR IP address block,
                            the specified IP address portion must be properly truncated
                            (i.e. all the host bits must be zero) or the input is
                            considered malformed. For example, "192.0.2.0/24" is accepted
                            but "192.0.2.1/24" is not. Similarly, for IPv6, "2001:db8::/32"
                            is accepted whereas "2001:db8::1/32" is not. The originating
                            IP of a request must be in one of the listed subnets in
                            order for this Condition to be true. If empty, all IP
                            addresses are allowed.
                          items:
                            type: string
                          type: array
                        members:
                          description: 'The request must be made by one of the provided
                            user or service accounts. Groups are not supported. Syntax:
                            `user:{emailid}` `serviceAccount:{emailid}` If not specified,
                            a request may come from any user.'
                          items:
                            type: string
                          type: array
                        negate:
                          description: Whether to negate the Condition. If true, the
                            Condition becomes a NAND over its non-empty fields, each
                            field must be false for the Condition overall to be satisfied.
                            Defaults to false.
                          type: boolean
                        regions:
                          description: The request must originate from one of the
                            provided countries/regions. Must be valid ISO 3166-1 alpha-2
                            codes.
                          items:
                            type: string
                          type: array
                        requiredAccessLevels:
                          description: 'A list of other access levels defined in the
                            same `Policy`, referenced by resource name. Referencing
                            an `AccessLevel` which does not exist is an error. All
                            access levels listed must be granted for the Condition
                            to be true. Example: "`accessPolicies/MY_POLICY/accessLevels/LEVEL_NAME"`'
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                type: object
              custom:
                description: A `CustomLevel` written in the Common Expression Language.
                properties:
                  expr:
                    description: Required. A Cloud CEL expression evaluating to a
                      boolean.
                    properties:
                      description:
                        description: Optional. Description of the expression. This
                          is a longer text which describes the expression, e.g. when
                          hovered over it in a UI.
                        type: string
                      expression:
                        description: Textual representation of an expression in Common
                          Expression Language syntax.
                        type: string
                      location:
                        description: Optional. String indicating the location of the
                          expression for error reporting, e.g. a file name and a position
                          in the file.
                        type: string
                      title:
                        description: Optional. Title for the expression, i.e. a short
                          string describing its purpose. This can be used e.g. in
                          UIs which allow to enter the expression.
                        type: string
                    type: object
                type: object
              description:
                description: Description of the `AccessLevel` and its use. Does not
                  affect behavior.
                type: string
              resourceID:
                description: The AccessContextManagerAccessLevel name. If not given,
                  the metadata.name will be used.
                type: string
              title:
                description: Human readable title. Must be unique within the Policy.
                type: string
            required:
            - accessPolicyRef
            type: object
          status:
            description: AccessContextManagerAccessLevelStatus defines the config
              connector machine state of AccessContextManagerAccessLevel
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              createTime:
                description: Output only. Time the `AccessLevel` was created in UTC.
                type: string
              externalRef:
                description: A unique specifier for the AccessContextManagerAccessLevel
                  resource in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                type: object
              updateTime:
                description: Output only. Time the `AccessLevel` was updated in UTC.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
