# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Presubmit

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"
      - "experiments/**"
  push:
    branches: ["master"]
    paths-ignore:
      - "**.md"
      - "experiments/**"
  merge_group:
    types: [checks_requested]
    branches: [ "master" ]


jobs:
  validations:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          # This is to get all the commits in order to validate them
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run validations"
        run: |
          ./scripts/github-actions/ga-validation.sh
        env:
          EVENT_NAME: ${{ github.event_name }}
          COMMIT_HEAD: ${{ github.event.pull_request.head.sha }}
          COMMIT_CNT: ${{ github.event.pull_request.commits }}
          BASE_COMMIT: ${{ github.event.pull_request.base.sha }}
  validate-generated-types:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          # This is to get all the commits in order to validate them
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Validate Generated Go Types"
        run: |
          dev/ci/presubmits/validate-generated-types.sh
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "Run unit tests"
        run: |
          ./scripts/github-actions/ga-unit-test.sh
      - name: "Upload test result"
        uses: actions/upload-artifact@v4
        if: '!cancelled()'
        with:
          name: unittest_result
          path: unittest_result.json
          retention-days: 5
  tests-e2e-samples:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run mock samples tests"
        run: |
          ./scripts/github-actions/tests-e2e-samples
        env:
          ARTIFACTS: /tmp/artifacts
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-tests-e2e-samples
          path: /tmp/artifacts/
  tests-e2e-fixtures:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run mock fixtures tests"
        run: |
          ./scripts/github-actions/tests-e2e-fixtures
        env:
          ARTIFACTS: /tmp/artifacts
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-tests-e2e-fixtures
          path: /tmp/artifacts/
  tests-e2e-fixtures-compute:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run mock fixtures tests for compute service"
        run: |
          ./scripts/github-actions/tests-e2e-fixtures-compute
        env:
          ARTIFACTS: /tmp/artifacts
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-tests-e2e-fixtures-compute
          path: /tmp/artifacts/
  tests-e2e-fixtures-gkehub:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run mock fixtures tests for gkehub service"
        run: |
          ./scripts/github-actions/tests-e2e-fixtures-gkehub
        env:
          ARTIFACTS: /tmp/artifacts
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-tests-e2e-fixtures-gkehub
          path: /tmp/artifacts/
  tests-e2e-fixtures-sql:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run mock fixtures tests for sql service"
        run: |
          ./scripts/github-actions/tests-e2e-fixtures-sql
        env:
          ARTIFACTS: /tmp/artifacts
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-tests-e2e-fixtures-sql
          path: /tmp/artifacts/
  pause-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run pause tests"
        run: |
          ./scripts/github-actions/ga-pause-test.sh
  scenarios-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "run scenarios-tests"
        run: |
          ./dev/ci/scenarios-tests
  tests-e2e-fixtures-vcr:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run vcr tests"
        run: |
          ./scripts/github-actions/tests-e2e-fixtures-vcr.sh
  powertool-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "Run scenarios tests for powertool"
        run: |
          ./scripts/github-actions/powertool-test.sh
  build-images:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "dev/tasks/build-images"
        run: |
          dev/tasks/build-images
    env:
      PROJECT_ID: cnrm-test
  test-mockgcp:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: "dev/ci/presubmits/test-mockgcp"
        run: |
          dev/ci/presubmits/test-mockgcp
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
