# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DEPRECATED: This file is deprecated and will be removed in the future.
# Please use ci-presubmit.yaml instead.
# Ideally all scripts would be in dev/ci/presubmits.

name: Presubmit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ["master"]
  merge_group:
    types: [checks_requested]
    branches: [ "master" ]


jobs:
  validations:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          # This is to get all the commits in order to validate them
          fetch-depth: 0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'
      - name: "Run validations"
        run: |
          ./scripts/github-actions/ga-validation.sh
        env:
          EVENT_NAME: ${{ github.event_name }}
          COMMIT_HEAD: ${{ github.event.pull_request.head.sha }}
          COMMIT_CNT: ${{ github.event.pull_request.commits }}
          BASE_COMMIT: ${{ github.event.pull_request.base.sha }}


  build-images:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Free up disk space
        run: dev/tasks/free-disk-space-on-github-actions-runner
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'
      - name: "dev/tasks/build-images"
        run: |
          dev/tasks/build-images
    env:
      PROJECT_ID: cnrm-test
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
