# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Presubmit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ['master']


jobs:
  validations:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          # This is introduced to make sure 'go generate' works properly
          path: 'src/k8s-config-connector'
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.11'
      - name: 'Run validations'
        run: |
          cd ./src/k8s-config-connector
          ./scripts/github-actions/ga-validation.sh
        env:
          # This is introduced to make sure 'go generate' works properly
          GOPATH: /home/runner/work/k8s-config-connector/k8s-config-connector
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.11'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Run unit tests'
        run: |
          ./scripts/github-actions/ga-unit-test.sh
        env:
          GOPATH: /home/runner/go
  mock-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.11'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Run mock tests'
        run: |
          ./scripts/github-actions/ga-mock-test.sh
        env:
          GOPATH: /home/runner/go

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
